language: java
jdk:
  - openjdk11
  - openjdk12
  - openjdk13
script:
  - mvn -B -ff tidy:check com.github.spotbugs:spotbugs-maven-plugin:check license:check verify
cache:
  - directories:
    - $HOME/.m2
