version: "3.7"
services:
  index:
    build: .
    ports:
      - "127.0.0.1:8080:8080"

  mongo:
    image: mongo
    network_mode: service:index
    ports:
      - "127.0.0.1:27017:27017"
#   volumes:
#      - ./redis-data:/data
