version: "3.7"
services:
  index:
    build: .
    ports:
      - "127.0.0.1:8080:8080"

  redis:
    image: redis
    container_name: redis
    network_mode: service:index
#    ports:
#      - "127.0.0.1:6379:6379"
#    volumes:
#      - ./redis-data:/data
